export const sriLankanRailwayStations = [
  // A
  { name: "Abanpola", province: "North Western Province" },
  { name: "Agbopura", province: "Eastern Province" },
  { name: "Ahangama", province: "Southern Province" },
  { name: "Ahungalle", province: "Southern Province" },
  { name: "Akurala", province: "Southern Province" },
  { name: "Alawwa", province: "North Western Province" },
  { name: "Alawathupitiya", province: "Western Province" },
  { name: "Aluthgama", province: "Western Province" },
  { name: "Ambalangoda", province: "Southern Province" },
  { name: "Ambepussa", province: "Western Province" },
  { name: "Ambewela", province: "Central Province" },
  { name: "Angulana", province: "Western Province" },
  { name: "Anuradhapura", province: "North Central Province" },
  { name: "Anuradhapura New Town", province: "North Central Province" },
  { name: "Arachchikattuwa", province: "North Western Province" },
  { name: "Avissawella", province: "Sabaragamuwa Province" },

  // B
  { name: "Badulla", province: "Uva Province" },
  { name: "Balapitiya", province: "Southern Province" },
  { name: "Babarenda", province: "Southern Province" },
  { name: "Bambalapitiya", province: "Western Province" },
  { name: "Bandarawela", province: "Uva Province" },
  { name: "Bangadeniya", province: "North Western Province" },
  { name: "Batticaloa", province: "Eastern Province", type: "terminus" },
  { name: "Batuwatta", province: "Western Province" },
  { name: "Bemmulla", province: "Western Province" },
  { name: "Beliatta", province: "Southern Province" },
  { name: "Bentota", province: "Southern Province" },
  { name: "Beruwala", province: "Western Province" },
  { name: "Boossa", province: "Southern Province" },
  { name: "Bothale", province: "Western Province" },
  { name: "Bulugahoda", province: "Western Province" },

  // C
  { name: "Chavakachcheri", province: "Northern Province" },
  { name: "Chenkaladi", province: "Eastern Province" },
  { name: "Chilaw", province: "North Western Province" },
  { name: "Chunnakam", province: "Northern Province" },
  { name: "Colombo Fort", province: "Western Province" },
  { name: "Colombo", province: "Western Province", note: "Currently National Railway Museum" },

  // D
  { name: "Dematagoda", province: "Western Province" },
  { name: "Daraluwa", province: "Western Province" },
  { name: "Dehiwala", province: "Western Province" },
  { name: "Demodara", province: "Uva Province" },
  { name: "Diyatalawa", province: "Uva Province" },

  // E
  { name: "Egoda Uyana", province: "Western Province" },
  { name: "Elephant Pass", province: "Northern Province" },
  { name: "Eluthumadduval", province: "Northern Province" },
  { name: "Enderamulla", province: "Western Province" },

  // F
  { name: "Free Trade Zone", province: "Western Province", note: "Formerly Katunayake South" },

  // G
  { name: "Galle", province: "Southern Province" },
  { name: "Gampaha", province: "Western Province" },
  { name: "Gampola", province: "Central Province" },

  // H
  { name: "Habaraduwa", province: "Southern Province" },
  { name: "Habarane", province: "North Central Province" },
  { name: "Halawatha", province: "Western Province" },
  { name: "Hali Ela", province: "Uva Province" },
  { name: "Haputale", province: "Uva Province" },
  { name: "Hath Amuna", province: "North Central Province" },
  { name: "Hatton", province: "Central Province" },
  { name: "Hettimulla", province: "Western Province" },
  { name: "Hikkaduwa", province: "Southern Province" },
  { name: "Hindeniya-Pattigoda", province: "Western Province" },
  { name: "Hingurakgoda", province: "North Central Province" },
  { name: "Horape", province: "Western Province" },
  { name: "Hunupitiya", province: "Western Province" },
  { name: "Horiwila", province: "North Central Province" },

  // I
  { name: "Idalgashinna", province: "Uva Province" },
  { name: "Induruwa", province: "Southern Province" },
  { name: "Inuvil", province: "Northern Province" },

  // J
  { name: "Ja-Ela", province: "Western Province" },
  { name: "Jaffna", province: "Northern Province" },
  { name: "Jayanthipura", province: "North Central Province" },

  // K
  { name: "Kahawa", province: "Southern Province" },
  { name: "Kalawewa", province: "North Central Province" },
  { name: "Kalutara North", province: "Western Province" },
  { name: "Kalutara South", province: "Western Province" },
  { name: "Kamburugamuwa", province: "Southern Province" },
  { name: "Kandana", province: "Western Province" },
  { name: "Kandy", province: "Central Province" },
  { name: "Kankesanthurai", province: "Northern Province", type: "terminus" },
  { name: "Kantalai", province: "Eastern Province" },
  { name: "Kapuwatte", province: "Western Province" },
  { name: "Kataragama", province: "Southern Province" },
  { name: "Kathaluwa", province: "Southern Province" },
  { name: "Katugoda", province: "Southern Province" },
  { name: "Katukurunda", province: "Western Province" },
  { name: "Katunayake", province: "Western Province" },
  { name: "Katunayake Airport", province: "Western Province", note: "BIA - Bandaranaike International Airport" },
  { name: "Keenawala", province: "Western Province" },
  { name: "Kekanadura", province: "Southern Province" },
  { name: "Kekirawa", province: "North Central Province" },
  { name: "Kelaniya", province: "Western Province" },
  { name: "Kilinochchi", province: "Northern Province" },
  { name: "Kinigama", province: "Uva Province" },
  { name: "Kodikamam", province: "Northern Province" },
  { name: "Koggala", province: "Southern Province" },
  { name: "Kokgala", province: "Southern Province" },
  { name: "Kookuvil", province: "Northern Province" },
  { name: "Kollupitiya", province: "Western Province" },
  { name: "Kondavil", province: "Northern Province" },
  { name: "Koralawella", province: "Western Province" },
  { name: "Kosgoda", province: "Southern Province" },
  { name: "Kotugoda", province: "Western Province" },
  { name: "Kudahakapola", province: "Western Province" },
  { name: "Kurunegala", province: "North Western Province" },

  // L
  { name: "Laxauyana", province: "North Central Province" },
  { name: "Liyanagemulla", province: "Western Province" },
  { name: "Lunawa", province: "Western Province" },
  { name: "Lunuwila", province: "North Western Province" },

  // M
  { name: "Magalegoda", province: "Western Province" },
  { name: "Maggona", province: "Western Province" },
  { name: "Maharagama", province: "Western Province" },
  { name: "Maho", province: "North Western Province" },
  { name: "Mallakam", province: "Northern Province" },
  { name: "Manampitiya", province: "North Central Province" },
  { name: "Mankulam", province: "Northern Province" },
  { name: "Mannar", province: "Northern Province" },
  { name: "Maradana", province: "Western Province" },
  { name: "Matale", province: "Central Province", type: "terminus" },
  { name: "Matara", province: "Southern Province" },
  { name: "Maviddapuram", province: "Northern Province" },
  { name: "Medawachchiya", province: "North Central Province" },
  { name: "Meesalai", province: "Northern Province" },
  { name: "Mirigama", province: "Western Province" },
  { name: "Mirissa", province: "Southern Province" },
  { name: "Mirusuvil", province: "Northern Province" },
  { name: "Moratuwa", province: "Western Province" },
  { name: "Mount Lavinia", province: "Western Province" },
  { name: "Murikandy", province: "Northern Province" },

  // N
  { name: "Naththandiya", province: "North Western Province" },
  { name: "Navatkuly", province: "Northern Province" },
  { name: "Negombo", province: "Western Province" },
  { name: "Nugegoda", province: "Western Province" },
  { name: "Nanu Oya", province: "Central Province" },
  { name: "Nawalapitiya", province: "Central Province" },

  // P
  { name: "Padukka", province: "Western Province" },
  { name: "Palai", province: "Northern Province" },
  { name: "Pallewela", province: "Western Province" },
  { name: "Panadura", province: "Western Province" },
  { name: "Parakum Uyana", province: "North Central Province" },
  { name: "Paranthan", province: "Northern Province" },
  { name: "Pattipola", province: "Central Province" },
  { name: "Payagala North", province: "Western Province" },
  { name: "Payagala South", province: "Western Province" },
  { name: "Peradeniya Junction", province: "Central Province", type: "terminus" },
  { name: "Peralanda", province: "Western Province" },
  { name: "Piladuwa", province: "Southern Province" },
  { name: "Pilimathalawa", province: "Central Province" },
  { name: "Pinwatta", province: "Western Province" },
  { name: "Polgahawela Junction", province: "North Western Province" },
  { name: "Polonnaruwa", province: "North Central Province" },
  { name: "Polwathumodara", province: "Southern Province" },
  { name: "Puliyahkulam", province: "Northern Province" },
  { name: "Punkankulam", province: "Northern Province" },
  { name: "Puttalam", province: "North Western Province", type: "branch terminus" },

  // R
  { name: "Ragama", province: "Western Province" },
  { name: "Rambukkana", province: "Sabaragamuwa Province" },
  { name: "Rathmalane", province: "Western Province" },
  { name: "Richmond Hill", province: "Southern Province" },
  { name: "Radella", province: "Central Province" },
  { name: "Rozella", province: "Central Province" },

  // S
  { name: "Sankathanai", province: "Northern Province" },
  { name: "Sarasavi Uyana", province: "Central Province" },
  { name: "Seeduwa", province: "Western Province" },
  { name: "Sewanapitiya", province: "North Central Province" },
  { name: "Slave Island", province: "Western Province" },

  // T
  { name: "Talaimannar", province: "Northern Province", type: "terminus", note: "Ferry port" },
  { name: "Talpe", province: "Southern Province" },
  { name: "Tellipalai", province: "Northern Province" },
  { name: "Thachanthoppu", province: "Northern Province" },
  { name: "Telwatte", province: "Southern Province" },
  { name: "Thandikulam", province: "Northern Province" },
  { name: "Trincomalee", province: "Eastern Province", type: "terminus", note: "Ocean port" },
  { name: "Thambutthegama", province: "North Central Province" },
  { name: "Thembiligala", province: "Central Province" },

  // U
  { name: "Ukuwela", province: "Central Province" },
  { name: "Unawatuna", province: "Southern Province" },
  { name: "Ulapane", province: "Central Province" },

  // V
  { name: "Valaichchenai", province: "Eastern Province" },
  { name: "Vavuniya", province: "Northern Province" },
  { name: "Veyangoda", province: "Western Province" },

  // W
  { name: "Wadduwa", province: "Western Province" },
  { name: "Walpola", province: "Western Province" },
  { name: "Wanawasala", province: "Western Province" },
  { name: "Wandurawa", province: "Western Province" },
  { name: "Wattegama", province: "Central Province" },
  { name: "Welikanda", province: "North Central Province" },
  { name: "Weligama", province: "Southern Province" },
  { name: "Wellawatta", province: "Western Province" },
  { name: "Wijayarajadahana", province: "Western Province" },
  { name: "Wavurukannala", province: "Southern Province" },

  // Y
  { name: "Yagoda", province: "Western Province" },
  { name: "Yaththalgoda", province: "Western Province" }
];
